// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2SnnYGgknrzWQp7s5lIrmGbsyZFTqo0',
    appId: '1:932483543178:web:1870b55e02323534dafd73',
    messagingSenderId: '932483543178',
    projectId: 'scool-65535186-b8fdb',
    authDomain: 'scool-65535186-b8fdb.firebaseapp.com',
    storageBucket: 'scool-65535186-b8fdb.firebasestorage.app',
    measurementId: 'G-Y1CKP7JBZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEcVKOtYVsgHCjWQsjovgD79wG1bfa5H8',
    appId: '1:932483543178:android:8a8c29c3757ee3b8dafd73',
    messagingSenderId: '932483543178',
    projectId: 'scool-65535186-b8fdb',
    storageBucket: 'scool-65535186-b8fdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm_aYZEjpOrlCxjmqkkSqI-WXklySA_QQ',
    appId: '1:932483543178:ios:15622ec654e71e00dafd73',
    messagingSenderId: '932483543178',
    projectId: 'scool-65535186-b8fdb',
    storageBucket: 'scool-65535186-b8fdb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm_aYZEjpOrlCxjmqkkSqI-WXklySA_QQ',
    appId: '1:932483543178:ios:15622ec654e71e00dafd73',
    messagingSenderId: '932483543178',
    projectId: 'scool-65535186-b8fdb',
    storageBucket: 'scool-65535186-b8fdb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg2SnnYGgknrzWQp7s5lIrmGbsyZFTqo0',
    appId: '1:932483543178:web:1870b55e02323534dafd73',
    messagingSenderId: '932483543178',
    projectId: 'scool-65535186-b8fdb',
    authDomain: 'scool-65535186-b8fdb.firebaseapp.com',
    storageBucket: 'scool-65535186-b8fdb.firebasestorage.app',
    measurementId: 'G-Y1CKP7JBZ6',
  );
}
